module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "var(--surface-container-low, #f3f4f5)",
        "error": "var(--red, #ba1a1a)",
        "on-background": "var(--on-surface, #191c1d)",
        "primary-container": "var(--primary-container, #0d631b)",
        "surface-dim": "var(--surface-dim, #d9dadb)",
        "on-secondary-container": "var(--on-secondary-container, #003670)",
        "surface-container-high": "var(--surface-container-high, #e7e8e9)",
        "on-secondary": "var(--white, #ffffff)",
        "surface-variant": "var(--surface-variant, #e1e3e4)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim, #88d983)",
        "tertiary-container": "var(--tertiary-container, #0e631c)",
        "on-primary-fixed": "var(--on-primary-fixed, #002203)",
        "on-error-container": "var(--on-error-container, #93000a)",
        "secondary-fixed": "var(--secondary-fixed, #d6e3ff)",
        "tertiary": "var(--primary, #00490f)",
        "surface": "var(--surface, #f8f9fa)",
        "primary": "var(--primary, #00490e)",
        "surface-container": "var(--surface-container, #edeeef)",
        "secondary": "var(--secondary, #005db7)",
        "primary-fixed-dim": "var(--primary-fixed-dim, #88d982)",
        "on-surface-variant": "var(--grey-text, #40493d)",
        "inverse-primary": "var(--inverse-primary, #88d982)",
        "on-primary-container": "var(--on-primary-container, #8bdd86)",
        "on-tertiary": "var(--white, #ffffff)",
        "error-container": "var(--error-container, #ffdad6)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim, #a9c7ff)",
        "background": "var(--background, #f8f9fa)",
        "primary-fixed": "var(--primary-fixed, #a3f69c)",
        "secondary-container": "var(--secondary-container, #64a1ff)",
        "on-error": "var(--white, #ffffff)",
        "tertiary-fixed": "var(--primary-fixed, #a3f69c)",
        "surface-container-lowest": "var(--white, #ffffff)",
        "surface-bright": "var(--surface, #f8f9fa)",
        "on-surface": "var(--on-surface, #191c1d)",
        "surface-tint": "var(--primary, #1b6d24)",
        "on-primary": "var(--white, #ffffff)",
        "inverse-surface": "var(--inverse-surface, #2e3132)",
        "outline": "var(--grey-text, #707a6c)",
        "surface-container-highest": "var(--surface-container-highest, #e1e3e4)"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
